#!/bin/bash
#
# Usage: update-all 
# 

# Stops execution if any command fails.
set -eo pipefail

main() {
  ./get-sheets.py
  DISPLAY=:99 xvfb-run -a ./wwin-all.py &
  DISPLAY=:99 xvfb-run -a ./meridianbet-all.py &
  wait
}

main "$@"
