#!/bin/bash
#
# Usage: update-all 
#

# Stops execution if any command fails.
set -eo pipefail

main() {
  ./get-sheets.py

  DISPLAY=:99 xvfb-run -a ./wwin-all.py &
  DISPLAY=:99 xvfb-run -a ./meridianbet-all.py &
  wait
  DISPLAY=:99 xvfb-run -a ./favbet-all.py &
  DISPLAY=:99 xvfb-run -a ./marathon-all.py &
  wait
  DISPLAY=:99 xvfb-run -a ./lsbet-all.py &
  DISPLAY=:99 xvfb-run -a ./betx-all.py &
  wait
}

main "$@"
